# Generated by Django 4.1.7 on 2023-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dateTaken',
            field=models.CharField(default='2021/2022', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='instructor',
            field=models.CharField(default='prof.', max_length=50),
        ),
    ]
