# Generated by Django 4.1.7 on 2023-03-12 06:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseReview', '0003_review_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
